spring.application.name=qualyra-backend
spring.profiles.active=dev

# JWT
jwt.secret=qualyra-secret-super-seguro-com-pelo-menos-256-bits-aqui-2024
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# CORS
cors.allowed-origins=http://localhost:5173
