services:
  postgres:
    image: postgres:16-alpine
    container_name: qualyra-db
    environment:
      POSTGRES_DB: qualyra
      POSTGRES_USER: qualyra
      POSTGRES_PASSWORD: qualyra123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
